site_name: Documentation
site_url: http://giv-oct.uni-muenster.de:8080/docs
site_description: Project documentation about the Core of the Open-City-Toolkit
site_author: Nicholas Schiestel, Jonas Wissing, Auriol Degbelo
# site_favicon: img/favicon.ico
# Local
#site_dir: site
# Server
site_dir: /home/webteam/OCT-Core/public/docs

repo_url: https://github.com/geo-c/OCT-Core-Docs

pages:
- Home: index.md
- Architecture:
    - Overview: architecture/overview.md
#    - Database-Schema: architecture/database-schema.md
    - REST-API: architecture/rest-api.md
- Database-Schemas:
    - 1. Apps: schemas/1_apps.md
    - 2. Logs: schemas/2_logs.md
    - 3. Users: schemas/3_users.md
    - 4. Datasources: schemas/4_datasources.md
    - 5. Prefixes: schemas/5_prefixes.md
    - 6. Metadata: schemas/6_metadata.md
    - 7. Tags: schemas/7_tags.md
    - 8. Datasets: schemas/8_datasets.md
#    - 9. Queries: schemas/9_queries.md
- About:
    - Repositories: about/repositories.md
    - Contributors: about/contributors.md
# - NewSection
    #- newPage: newSection/newPage.md
# - newSinlePage: newSinlePage.md

theme: readthedocs

markdown_extensions:
    - toc:
        permalink: true

copyright: Copyright &copy; 2016 <a href="https://www.uni-muenster.de/Geoinformatics/">Institute for Geoinformatics, MÃ¼nster</a>
